main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about_page, name='about'),
    path('signup', views.signup_page, name='signup_page'),
    path('signin', views.signin_page, name='signin_page'),
    path('activate/<str:uidb64>/<str:token>', views.activate, name='activate'),
    path('logout', views.logout_page, name='logout_page'),
]

urlpatterns += [
    path('account', views.account, name='account'),
    path('account/delete-account', views.delete_account, name='delete_account'),
    path('account/search_items', views.item_page, name='item'),
    path('account/profile_items', views.profile_item_page, name='profile_items'),
    path('account/favorite_items', views.favorite_items_page, name='favorite_items'),
]

urlpatterns += [
    path('change_password/', views.change_password, name='change_password'),
    # path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset-password/reset_password.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset-password/password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="reset-password/password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset-password/password_reset_done.html"), name='password_reset_complete')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from datetime import date

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from import_export import resources

from mptt.models import MPTTModel, TreeForeignKey

from .tasks import send_email_task
from . import managers


class User(AbstractUser):
    username = None
    department = models.CharField(max_length=100, default="department name")
    email = models.EmailField(_('email address'), unique=True)
    grant_access_to_this_account = models.BooleanField(default=False)
    notify_date = models.DateField(null=True, blank=True)
    expiration_date = models.DateField(null=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = managers.UserManager()

    def clean(self):
        if self.expiration_date and self.notify_date:
            if self.expiration_date < self.notify_date:
                raise ValidationError('Notify time should be before send time')
        return super().clean()

    def save_base(self, raw=False, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.notify_date != '' and self.notify_date is not None:
            days = (self.expiration_date - self.notify_date).days
            send_email_task.apply_async(args=[self.username,
                                              self.email,
                                              self.expiration_date,
                                              days
                                              ], countdown=days * 86400)
        if (self.notify_date == '' or self.notify_date is None) and self.expiration_date:
            days = (self.expiration_date - date.today()).days
            send_email_task.apply_async(args=[self.username,
                                              self.email,
                                              self.expiration_date,
                                              days
                                              ], countdown=days * 86400)
        super().save_base(raw, force_insert, force_update, using, update_fields)


class Category(MPTTModel):
    name = models.CharField(max_length=200)
    parent = TreeForeignKey(to='self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Item(models.Model):
    name = models.CharField(max_length=200)
    rank = models.IntegerField()
    quantity = models.IntegerField(null=True, blank=True)
    verified = models.BooleanField(null=True, blank=True)
    category = models.ManyToManyField(Category, related_name='item')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['rank']


class Sample(models.Model):
    id = models.CharField(max_length=200, primary_key=True)
    item = models.ForeignKey(Item, on_delete=models.DO_NOTHING)
    date = models.DateField()
    name = models.CharField(max_length=200)
    text = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Favourite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['-added_at']

    def __str__(self):
        return f'{ self.item.name } -> { self.user.email }'

main/views.py
import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib import messages
from django.template.loader import render_to_string

from .forms import UserProfileForm
from project import settings

from main.models import User
from main.tokens import account_activation_token

from main.forms import SignUpForm, SignInForm, FavouriteItemForm, ChangePasswordForm
from .tasks import send_email_task
from . import models


def index(request):
    return render(request, 'index.html')


def about_page(request):
    return render(request, 'about.html')


def signup_page(request):
    form = SignUpForm()

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            if not User.objects.filter(email=form.cleaned_data['email']).count():
                user = form.save()
                subject = 'Activate your account'
                current_site = get_current_site(request)
                message = render_to_string('activation-account.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                send_mail(subject, message, settings.EMAIL_HOST_USER, [form.data.get('email')])
                messages.add_message(
                    request=request,
                    level=messages.SUCCESS,
                    message="Please confirm your email, to activate your account"
                )

            else:
                messages.add_message(
                    request=request,
                    level=messages.ERROR,
                    message="Sorry, this mail already exists"
                )
        else:
            for msg in form.errors:
                messages.add_message(
                    request=request,
                    level=messages.ERROR,
                    message=form.errors[msg][0]
                )
    return render(request, 'signup-page.html', {'form': form})


def signin_page(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            user = User.objects.filter(email=form.data.get('email')).first()
            if user:
                login(request, user)
                return redirect('index')
        else:
            return render(request, 'signin-page.html', {'form': form})
    return render(request, 'signin-page.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.add_message(
            request=request,
            level=messages.SUCCESS,
            message="Your account successfully activated!"
        )
        return redirect('index')
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')


@login_required
def account(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=request.user.pk)
            user.first_name = form.data.get('first_name')
            user.last_name = form.data.get('last_name')
            user.department = form.data.get('department')
            user.save()

    return render(request, 'user/account.html', {'form': form})


@login_required
def item_page(request):

    if request.method == 'POST':

        form = FavouriteItemForm(request.POST)
        form.user = request.user

        if form.is_valid():
            form.save()

    if request.user.grant_access_to_this_account and (
        (datetime.date.today() < request.user.expiration_date) if request.user.expiration_date else False
    ):

        qs = models.Item.objects.all()

        c = {
            "min": qs.order_by('quantity')[0].quantity if qs.order_by('quantity').count() else 0,
            "max": qs.order_by('quantity').reverse()[0].quantity if qs.order_by('quantity').reverse().count() else 0,
            'favourite_form': FavouriteItemForm()
        }

        params = list(request.GET.keys())

        if 'min' in params and (not request.GET['min'] == ''):
            qs = qs.filter(quantity__gte=request.GET['min'])

        if 'max' in params and (not request.GET['max'] == ''):
            qs = qs.filter(quantity__lte=request.GET['max'])

        if 'verified' in params and request.GET['verified'] == 'on':
            qs = qs.filter(verified=True)

        if 'items_samples' in params and request.GET['items_samples'] == 'on':
            qs = qs.filter(sample__isnull=True)

        if request.GET.get('category') is not None:
            filter_category = request.GET.get('category')
            if filter_category != '':
                c['filter_category'] = int(filter_category)
                category = models.Category.objects.filter(pk=int(filter_category)).first()
                qs = qs.filter(category=category)

        c['items'] = qs
        c['has_access'] = True

        categories = models.Category.objects.all()
        c['categories'] = categories

        page = request.GET.get('page', 1)

        paginator = Paginator(c['items'], 20)
        try:
            c['items'] = paginator.page(page)
        except PageNotAnInteger:
            c['items'] = paginator.page(1)
        except EmptyPage:
            c['items'] = paginator.page(paginator.num_pages)
    else:
        c = {'has_access': False}

    categories = models.Category.objects.all()
    c['categories'] = categories
    # {'page_obj': page_obj}
    return render(request, 'user/tables.html', c)


@login_required
def profile_item_page(request):

    if request.method == 'POST':

        form = FavouriteItemForm(request.POST)
        form.user = request.user

        if form.is_valid():
            form.save()

    if request.user.grant_access_to_this_account and (
        (datetime.date.today() < request.user.expiration_date) if request.user.expiration_date else False
    ):

        qs = models.Item.objects.all()

        c = {
            "min": qs.order_by('quantity')[0].quantity if qs.order_by('quantity').count() else 0,
            "max": qs.order_by('quantity').reverse()[0].quantity if qs.order_by('quantity').reverse().count() else 0,
            'favourite_form': FavouriteItemForm()
        }

        params = list(request.GET.keys())

        if 'min' in params and (not request.GET['min'] == ''):
            qs = qs.filter(quantity__gte=request.GET['min'])

        if 'max' in params and (not request.GET['max'] == ''):
            qs = qs.filter(quantity__lte=request.GET['max'])

        if 'verified' in params and request.GET['verified'] == 'on':
            qs = qs.filter(verified=True)

        if 'items_samples' in params and request.GET['items_samples'] == 'on':
            qs = qs.filter(sample__isnull=True)

        if request.GET.get('category') is not None:
            filter_category = request.GET.get('category')
            if filter_category != '':
                c['filter_category'] = int(filter_category)
                category = models.Category.objects.filter(pk=int(filter_category)).first()
                qs = qs.filter(category=category)

        c['items'] = qs
        c['has_access'] = True

        categories = models.Category.objects.all()
        c['categories'] = categories

        page = request.GET.get('page', 1)

        paginator = Paginator(c['items'], 20)
        try:
            c['items'] = paginator.page(page)
        except PageNotAnInteger:
            c['items'] = paginator.page(1)
        except EmptyPage:
            c['items'] = paginator.page(paginator.num_pages)
    else:
        c = {'has_access': False}

    return render(request, 'user/profile_items.html', c)


def favorite_items_page(request):
    if request.method == "POST":
        data = request.POST
        if data['action'] == 'remove_comment':
            if request.user.favourite_set.filter(item_id=data['item']).count():
                request.user.favourite_set.filter(item_id=data['item']).first().delete()

    c = {
        'items': request.user.favourite_set.all(),
        "has_access": request.user.grant_access_to_this_account
    }
    return render(request, 'user/table_favorite.html', c)


def reset_password(request):
    return render(request, 'reset-password.html')


def logout_page(request):
    logout(request)
    return redirect('index')


@login_required
def delete_account(request):
    logout(request)
    models.User.objects.get(pk=request.user.pk).delete()
    messages.add_message(
        request=request,
        level=messages.SUCCESS,
        message="Your account successfully deleted"
    )
    return render(request, 'index.html')


@login_required
def change_password(request):
    c = {}

    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)

        user = models.User.objects.get(pk=request.user.pk)

        if form.is_valid():
            if user.check_password(form.cleaned_data['current_password']):

templates/user/account.html
{% extends "base.html" %}
{% load i18n static %}


{% block content %}
    <main>
        <div class="container mt-4 mb-2">
            <div class="row">
                <div class="col-12 text-center">
                    <h2>{% trans 'Profile Information' %}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-8 offset-2">
                    <form method="post" action="{% url 'account' %}">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputFirstName">First name</label>
                                <input type="text" name="first_name" class="form-control" id="inputFirstName" required
                                       value="{{ user.first_name }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputLastName">Last name</label>
                                <input type="text" name="last_name" class="form-control" id="inputLastName" required
                                       value="{{ user.last_name }}">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputDepartment">Department</label>
                                <input type="text" name="department" class="form-control" id="inputDepartment"
                                       required value="{{ user.department }}">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                    <br>
                    <button class="btn btn-danger" id="delete_account">Delete account</button>
                </div>
            </div>
        </div>
    </main>

    <script>
    document.querySelector("#delete_account").addEventListener("click", function (e){
        e.preventDefault();
        const confirmed = confirm("Do you really want to delete your account?");

        if (confirmed) {
            window.location="{% url 'delete_account' %}"
        }
    })
    </script>
{% endblock %}

templates/user/table_favorite.html
{% extends "base.html" %}
{% load i18n static %}

{% block content %}
    <div class="container">
    {% if has_access %}
        <div class="row">
            <div class="col-12">
                <h1 style="margin-top: 20px; text-align: center">Favorite Items</h1>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-12">
                <div>
                    <table class="table table-striped my-3">
                        <thead>
                            <tr>
                                <th scope="col">name</th>
                                <th scope="col">quantity</th>
                                <th scope="col">comment</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for item in items %}
                                <tr>
                                    <td>{{ item.item.name }}</td>
                                    <td>{{ item.item.quantity }}</td>

                                    <td>
                                        {% if item.comment %}<span>{{ item.comment }}</span>{% endif %}
                                    </td>
                                    <td>
                                        <form action="{% url 'favorite_items' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="user" id="id_user" value="{{ request.user.id }}" required>
                                            <input type="hidden" name="item" id="id_item" value="{{ item.item.id }}" required>
                                            <input type="hidden" name="action" value="remove_comment">

                                            <input type="submit" class="btn btn-secondary" value="Remove">
                                        </form>
                                    </td>

                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
      {% else %}
            <h3 style="text-align: center; margin-top: 40px;">Sorry, you dont have access to Items</h3>
        {% endif %}
    </div>
{% endblock %}

templates/user/tables.html
{% extends "base.html" %}
{% load i18n static app_tags %}

{% block content %}
    <div class="container">
        <br>
        {% if has_access %}
            <div class="row">
                <div class="col-12">
                    <form class="form-inline justify-content-around align-items-start" method="get" action="{% url 'item' %}">

                        <div>
                            <h5>Quantity:</h5>
                            <div class="form-group justify-content-between mb-1">
                                <label for="quantity-min">Min: &nbsp;</label>
                                <input class="form-control mr-sm-2" type="number" id="quantity-min" placeholder="Min" aria-label="Min"
                                       name="min"
                                       value="{% if request.GET.min %}{{ request.GET.min }}{% else %}{{ min }}{% endif %}"
                                       min="{{ min }}" max="{{ max }}">
                            </div>

                            <div class="form-group justify-content-between">
                                <label for="quantity-max">Max: &nbsp;</label>
                                <input class="form-control mr-sm-2" type="number" id="quantity-max" placeholder="Max" aria-label="Max"
                                       name="max"
                                       value="{% if request.GET.max %}{{ request.GET.max }}{% else %}{{ max }}{% endif %}"
                                       min="{{ min }}" max="{{ max }}">
                            </div>
                        </div>

                        <div>
                            <h5>Category:</h5>
                            <div class="form-group">
                                <input type="text" id="category-dropdown" placeholder="Select" autocomplete="off"/>
{#                                <select class="form-control" id="product" name="category">#}
{#                                    <option value="">All categories</option>#}
{#                                    {% for category in categories %}#}
{#                                        <option {% if category.id == filter_category %}#}
{#                                            selected {% endif %} value="{{ category.id }}">#}
{#                                            {{ category.name }}#}
{#                                        </option>#}
{#                                    {% endfor %}#}
{#                                </select>#}
                            </div>
                        </div>

                        <div>
                            <h5>Others:</h5>
                            <div class="form-group justify-content-between mx-auto mb-1">
                                <label for="verified">Only verified items:</label>
                                <input class="form-control ml-2" type="checkbox" placeholder="Is verified"
                                       aria-label="Is verified" name="verified" id="verified"
                                       {% if request.GET.verified == 'on' %}checked="on"{% else %}chechked="off"{% endif %}>
                            </div>

                            <div class="form-group justify-content-between">
                                <label for="verified">Items with Samples:</label>
                                <input class="form-control ml-2" type="checkbox" placeholder="Has items samples"
                                       aria-label="Has items samples" name="items_samples" id="items_samples"
                                       {% if request.GET.items_samples == 'on' %}checked="on"
                                       {% else %}chechked="off"{% endif %}>
                            </div>
                        </div>

                        <div>
                            <div class="form-group ml-auto">
                                <button class="btn btn-outline-success my-2 my-sm-0 mx-2" type="submit">Search</button>
                                <a href="{% url 'item' %}" class="btn btn-outline-info my-2 my-sm-0">Reset</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <br>
{#            <div class="row">#}
{#                <div class="col-12">#}
{#                    <h3>Search result: <span>{{ items.count }}</span></h3>#}
{#                </div>#}
{#            </div>#}
            <div class="row">
                <div class="col-12">
                    <div>
                        <table class="table table-striped my-3">
                            <thead>
                            <tr>
                                <th scope="col">name</th>
                                <th scope="col">quantity</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for item in items %}
                                <tr>
                                    <td>{{ item.name }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>

                                        {% with request.user.favourite_set.all|get_favourites as favourites %}
                                            {% if item not in favourites %}
                                                <form action="{% url 'item' %}" method="post">
                                                    {% csrf_token %}

                                                    <input type="hidden" name="user" id="id_user" value="{{ request.user.id }}" required>
                                                    <input type="hidden" name="item" id="id_item" value="{{ item.id }}" required>
                                                    <input type="hidden" name="action" value="add_comment">

                                                    <input type="submit" class="btn btn-success" value="Add to favourites">
                                                    <input type="text" name="comment" id="id_comment" placeholder="{% trans 'comments here' %}" class="form-control d-inline-block align-middle" style="width: auto;">
                                                </form>
                                            {% endif %}
                                        {% endwith %}

                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>

                        <div class="pagination">
                            {% if items.has_other_pages %}
                                <ul class="pagination">
                                    {% if items.has_previous %}
                                        <li><a href="?page={{ items.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for i in items.paginator.page_range %}
                                        {% if items.number == i %}
                                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                        {% else %}
                                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if items.has_next %}
                                        <li><a href="?page={{ items.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
        {% else %}
            <h3 style="text-align: center; margin-top: 40px;">Sorry, you dont have access to Items</h3>
        {% endif %}
    </div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'dropdown/style.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'dropdown/comboTreePlugin.js' %}" type="text/javascript"></script>
    <script>

        function loadComboTree() {
            let SampleJSONData2 = [
                {
                    id: 1,
                    title: 'Four Wheels',
                    subs: [
                        {
                            id: 10,
                            title: 'Car'
                        }, {
                            id: 11,
                            title: 'Truck'
                        }, {
                            id: 12,
                            title: 'Transporter'
                        }, {
                            id: 13,
                            title: 'Dozer'
                        }
                    ]
                }, {
                    id: 2,
                    title: 'Two Wheels',
                    subs: [
                        {
                            id: 20,
                            title: 'Cycle'
                        }, {
                            id: 21,
                            title: 'Motorbike'
                        }, {
                            id: 22,
                            title: 'Scooter'
                        }
                    ]
                }, {
                    id: 2,
                    title: 'Van'
                }, {
                    id: 3,
                    title: 'Bus'
                }
            ];

            comboTree3 = $('#category-dropdown').comboTree({
                source: SampleJSONData2,
                isMultiple: true,
                cascadeSelect: true,
                collapse: false

            });

            // comboTree3.setSource(SampleJSONData2);

        }

        loadComboTree();

    </script>
{% endblock %}